#!/bin/sh

WAN_DEVICE="wan6"  # interface for IPv6
TUNNEL_INTERFACE="zoot"

# logger -t ip4o6_hotplug "Interface: $INTERFACE, Action: $ACTION"

# Get interface name with ip4o6 protocol dynamically
get_ip4o6_ifname() {
    for line in $(uci show network | grep "=interface" | cut -d= -f1); do
        iface="${line#network.}"
        proto=$(uci get network."$iface".proto 2>/dev/null)
        [ "$proto" = "ip4o6" ] && echo "$iface" && return
    done
}

# Check if specified interface is disabled
is_interface_disabled() {
    local iface="$1"
    [ "$(uci get network."$iface".disabled 2>/dev/null)" = "1" ]
}

if [ "$INTERFACE" = "$WAN_DEVICE" ]; then
    IP4O6_IF=$(get_ip4o6_ifname)

    if [ -n "$IP4O6_IF" ] && ! is_interface_disabled "$IP4O6_IF"; then
        case "$ACTION" in
            ifup)
                logger -t ip4o6_hotplug "WAN6 restored, bringing up $IP4O6_IF"
                ifup $IP4O6_IF
                ;;
            ifdown)
                logger -t ip4o6_hotplug "WAN6 lost, bringing down $IP4O6_IF"
                ifdown $IP4O6_IF
                ;;
        esac
    else
        logger -t ip4o6_hotplug "Not found or disabled"
    fi
fi
